version: '3'
services:

  db:
    image: mongo:4.2.8
    container_name: db
    ports:
     - "3002:27017"
    restart: always

  gcp-storage:
    image: gcp-storage
    build: 
      context: ./gcp-storage
      dockerfile: Dockerfile
    container_name: video-storage
    ports:
     - "3000:8080"
    environment:
      - PORT=8080
      - GCP_PROJECT_ID=<insert your GCP Project ID here>
      - GCP_KEYFILE_PATH=<insert your GCP key file path here>
      - GCP_BUCKET_NAME=<insert your GCP storage bucket name here>
    restart: "no"

  video-streaming:
    image: video-streaming
    build: 
      context: ./video-streaming
      dockerfile: Dockerfile
    container_name: video-streaming
    ports:
     - "3001:80"
    environment:
      - PORT=8080
      - DBHOST=mongodb://db:27017
      - DBNAME=video-streaming
      - VIDEO_STORAGE_HOST=video-storage
      - VIDEO_STORAGE_PORT=8080
    depends_on:
      - db
    restart: "no"
